<a href="https://colab.research.google.com/github/WilmarAriza/WilmarAriza/blob/main/Par1_WA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

6.86x Intro de ML Packages Part 1

FIRST SECTION = Jupyter: browser front-end

In [ ]:
6/5

1.2

In [ ]:
def tokenize(text):
    return text.split(' ')

In [ ]:
text = 'This is a test of my function'
print(tokenize(text))

['This', 'is', 'a', 'test', 'of', 'my', 'function']


Notice the function return a list!

SECOND SECTION = Numpy: to handle large multidimensional arrays

In [ ]:
import numpy as np

1. Indexing and slicing

In [ ]:
a_py = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a_np = np.array(a_py)

In [ ]:
print(a_py[3:7:2], a_np[3:7:2])

[4, 6] [4 6]


Notice: a list, and a Numpy array

In [ ]:
print(a_py[2:-1:2], a_np[2:-1:2])
print(a_py[::-1], a_np[::-1])

[3, 5, 7] [3 5 7]
[9, 8, 7, 6, 5, 4, 3, 2, 1] [9 8 7 6 5 4 3 2 1]


But can use arrays to index other arrays

In [ ]:
idx = np.array([7,2,0])
a_np[idx]

array([8, 3, 1])

a_np[idx], allows convenient querying, reindexing and sorting

In [ ]:
ages = np.random.randint(low=30, high=60, size=10)
heights = np.random.randint(low=150, high=210, size=10)

print(ages)
print(heights)

[54 39 47 44 40 48 32 50 51 40]
[186 167 179 189 201 150 152 162 164 162]


In [ ]:
print(ages < 45)

[False  True False  True  True False  True False False  True]


It is a boolean!

In [ ]:
print(heights[ages < 45])
print(ages[ages < 45])

[167 189 201 152 162]
[39 44 40 32 40]


Filter the arrays with the boolean.

In [ ]:
shuffled_idx = np.random.permutation(10)
print(shuffled_idx)
print(ages[shuffled_idx])
print(heights[shuffled_idx])

[9 0 1 8 4 6 2 3 7 5]
[40 54 39 51 40 32 47 44 50 48]
[162 186 167 164 201 152 179 189 162 150]


In [ ]:
sorted_idx = np.argsort(ages)
print(sorted_idx)
print(ages[sorted_idx])
print(heights[sorted_idx])

[6 1 4 9 3 2 5 7 8 0]
[32 39 40 40 44 47 48 50 51 54]
[152 167 201 162 189 179 150 162 164 186]


Same result as np.random.permutation

2. broadcasting: operations between arrays of different sizes